baseURL: "https://example.com"
languageCode: "en-us"
title: "Hugo Novela"
pygmentsstyle: 'monokai'
paginate: 6
social:
  twitter: "aryodwin"
  ##github: "#"
  instagram: "aryodwin"
  linkedin: "aryodwin"
  ##dribbble: "#"
  ##youtube: "#"
taxonomies:
  author: authors
