baseURL: "https://example.com"
languageCode: "en-us"
title: "Hugo Novela"
pygmentsstyle: 'monokai'
paginate: 6
social:
  twitter: "https://twitter.com/aryodwin"
  ##github: "#"
  instagram: "https://www.instagram.com/aryodwin/"
  linkedin: "https://www.linkedin.com/in/aryodwin/"
  ##dribbble: "#"
  ##youtube: "#"
taxonomies:
  author: authors
